export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  SECTION_PARSE_EMPTY: "SECTION_PARSE_EMPTY",
  DIFF_PAIR_MISSING: "DIFF_PAIR_MISSING",
  DIFF_NOT_READY: "DIFF_NOT_READY",
  NOTE_COMMENT_EMPTY: "NOTE_COMMENT_EMPTY",
  STORAGE_WRITE_FAILED: "STORAGE_WRITE_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
