/** 错误码：service 与 store 分别包装异常时共同引用 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  PARSE_FAILED: "PARSE_FAILED",
  VERSION_REQUIRED: "VERSION_REQUIRED",
  SAME_VERSION: "SAME_VERSION",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
